Fpb 1/document handler development
nozikov/fixpricebot pull request #13
Opened 2021-12-02 11:50 UTC by hopetoknow

2021-12-20 18:38 UTC, nozikov requested changes

2021-12-20 21:02 UTC, nozikov requested changes

2021-12-20 21:02 UTC, nozikov commented on src/main/resources/application.yml
> +user-whitelist:
И здесь стоит назвать категорию просто как user, а поле whitelist

2021-12-20 21:06 UTC, nozikov commented
Еще у тебя есть 2 пары одинаковых коммитов нужно сделать по одному из них

2021-12-21 14:02 UTC, hopetoknow commented on src/main/java/com/fixprice/bot/telegram/TelegramBotFixPrice.java
> +            if (!userWhitelist.getList().contains(message.getChatId().toString())) {
Так и есть. А как нужно нам?

2021-12-21 14:05 UTC, hopetoknow commented on src/main/java/com/fixprice/bot/telegram/user/data/UserWhitelist.java
> +public class UserWhitelist {
А какое property мы можем в этот класс в будущем добавить? Класс задумывался только для хранения списка юзеров с правами

2021-12-21 14:07 UTC, hopetoknow commented
> Еще у тебя есть 2 пары одинаковых коммитов нужно сделать по одному из них
Вот здесь не понял, но да, там небольшая каша получилась

2021-12-21 15:25 UTC, nozikov commented on src/main/java/com/fixprice/bot/telegram/TelegramBotFixPrice.java
> +            if (!userWhitelist.getList().contains(message.getChatId().toString())) {
Доступ только для отправки файла

2021-12-21 15:36 UTC, nozikov commented on src/main/java/com/fixprice/bot/telegram/TelegramBotFixPrice.java
> +            if (!userWhitelist.getList().contains(message.getChatId().toString())) {
Еще стоит вынести логику определения доступа в userService

2021-12-22 21:17 UTC, nozikov requested changes

2021-12-22 21:17 UTC, nozikov commented on src/main/java/com/fixprice/bot/telegram/user/service/UserService.java
> +    private void isUserHasAccessToUploadFile() {
Зачем этот метод?

2021-12-22 21:44 UTC, nozikov commented
Еще нужно решить конфликты

2021-12-23 18:30 UTC, merged