Fix the incorrect parsing of the product price value from 100 to 199
nozikov/fixpricebot pull request #5
Opened 2021-10-30 20:05 UTC by hopetoknow

That's it, maybe i'll come with more elegant solution later

2021-11-02 22:05 UTC, nozikov requested changes

2021-11-03 07:30 UTC, hopetoknow commented on src/main/java/com/fixprice/bot/telegram/service/ProductService.java
> +        if (document.select(fixPriceProperties.getPricePath() + " > span").textNodes().size() == 0) {
А стоит выносить его в отдельный метод, если количество кода только увеличиться от этого?

2021-11-03 07:30 UTC, hopetoknow commented on src/main/java/com/fixprice/bot/telegram/service/ProductService.java
> +        + document.select(fixPriceProperties.getPricePath()).textNodes().get(0).text();
А стоит выносить его в отдельный метод, если количество кода только увеличиться от этого?

2021-11-08 18:42 UTC, nozikov approved these changes

2021-11-08 18:42 UTC, merged